### ISSUE TITLE
Migrate Matrix community to Spaces

### ISSUE THREAD

**Issue by OmeGak** [bonfirelink/infrastructure#27]
Element release [last Friday](https://matrix.org/blog/2021/10/01/this-week-in-matrix-2021-10-01) finally switched on Spaces and hid Communities. This means that our [Matrix community](https://matrix.to/#/+bonfire.link:bonfire.link) appears hidden to everyone using an up-to-date version of Element.

Let's: 
- [x] Figure out how to self-host a Space in https://matrix.bonfire.link
- [x] Add all Discord bridged rooms in the Space.
- [x] Federate room/space list so that people can search us.

Related:
- [ ] https://github.com/bonfirelink/infrastructure/issues/14

**Comment by Sakrecoer** [comment]
To convert a community to a space in element:
- Log in to the account that is admin for the community
- go to settings > preferences > flip on "Display communities instead of spaces"
- click the three dots (...) that appear when hovering a community > View community
- on the apges display you will see a message box:
![image](https://user-images.githubusercontent.com/3484593/135993518-5a6cd445-4437-4ff0-9128-48423c85918b.png)
- Click the link "here" set the options and hit "create space"

Voilà!

**Comment by Sakrecoer** [comment]
To self-host a space: 
- Add an address to `Local Addresses` for the space in the space-settings > Visibility. 
- Set this new address to be the `main address`

**Comment by Sakrecoer** [comment]
For reference, `matrix.bonfire.link` is currently not federating it's room/space list. 
In Synapse to enable this use: `allow_public_rooms_over_federation: true` in your `homeserver.yaml` file

**Comment by OmeGak** [comment]
Missing rooms added on the space.

> For reference, `matrix.bonfire.link` is currently not federating it's room/space list. In Synapse to enable this use: `allow_public_rooms_over_federation: true` in your `homeserver.yaml` file

Done too!
